entrada = input('Digite algo: ')
print(f'O tipo primitivo de "{entrada}" é:', type(entrada), 'pois todo input retorna uma string.')
print(f'O valor digitado é apenas espaço? Resposta:', entrada.isspace())
print(f'O valor digitado é apenas número? Resposta:', entrada.isalnum())
print(f'O valor digitado é alfabético? Resposta:', entrada.isalpha())
print(f'O valor digitado é alfanumérico? Resposta:', entrada.isalnum())
print(f'O valor digitado está em maiúscula? Resposta:', entrada.isupper())
print(f'O valor digitado está em minusculo? Resposta:', entrada.islower())
print(f'O valor digitado está capitalizado? Resposta:', entrada.istitle())
